# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_type', models.CharField(blank=True, choices=[('Restaurants', 'Restaurants'), ('Stationary', 'Stationary'), ('SuperMarkets', 'SuperMarkets'), ('Salon-Spa', 'Salon & Spa'), ('Pharmacies', 'Pharmacies'), ('Apparel-Stores', 'Apparel Stores'), ('Hardware', 'Hardware')], max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('PayTm', 'PayTm'), ('UPI', 'UPI'), ('Debit-Card', 'Debit Card')], max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('long', models.DecimalField(decimal_places=20, max_digits=25)),
                ('vpa', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
