# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20171008_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('NA', 'NA')], max_length=2),
        ),
    ]
